
[platformio]
default_envs = v1_6
src_dir = examples/factory
;src_dir = examples/MinimalCameraExample
;src_dir = examples/MinimalCameraStationExample
;src_dir = examples/MinimalPowersExample
;src_dir = examples/MinimalScreenExample
;src_dir = examples/MinimalSoundDetectionExample

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
framework = arduino
board = esp32s3box
board_build.partitions = partitions.csv
upload_speed = 921600
monitor_speed = 115200

build_flags =
    -DBOARD_HAS_PSRAM
    ; USB CDC prints serial logs while USB is connected.
    -DARDUINO_USB_CDC_ON_BOOT=1
    ; Disable USB CDC for battery-only startup if required.
    ; -UARDUINO_USB_CDC_ON_BOOT
    -DPLATFORMIO_ENV

[env:v1_6]
build_flags =
    ${env.build_flags}
    -DLILYGO_BOARD_VERSION=16

[env:v1_7]
build_flags =
    ${env.build_flags}
    -DLILYGO_BOARD_VERSION=17
